---
ci_config: &ci_config
  - ".github/workflows/ci.yml"
  - ".github/file-filters.yml"

github_workflows: &github_workflows
  - ".github/workflows/*.yml"

doc_files: &doc_files
  - "docs/**"
  - package.json
  - package-lock.json

uv_files: &uv_files
  - "**/pyproject.toml"
  - "**/uv.lock"

python_all: &python_all
  - "**/*.py"
  - *uv_files

yaml_all: &yaml_all
  - "**/*.{yml,yaml}"

markdown_all: &markdown_all
  - "**/*.{md,mdx}"

documentation_all:
  - *doc_files
  - *markdown_all
